# Dockerfile.airflow
FROM apache/airflow:3.0.1-python3.12

USER root

# Install Python packages from requirements
COPY requirements.txt /

USER airflow
RUN pip install --no-cache-dir -r /requirements.txt

