version: '3.8'

services:
  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    entrypoint: >
      bash -c "
        airflow db migrate &&
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
      "
    volumes:
      - airflow_db:/opt/airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: scheduler
    depends_on:
      - airflow-init
    ports:
      - "8793:8793"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_db:/opt/airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db

  airflow-apiserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: api-server
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_db:/opt/airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      MLFLOW_TRACKING_URI: http://mlflow:5000

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5050:5000"
    volumes:
      - ./mlruns:/app/artifacts
      - mlflow_db:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  airflow_db:
  mlflow_db:
